#ifndef CONFIG_H
#define CONFIG_H
#include "driver/gpio.h"

#define RECORD_BUTTON GPIO_NUM_0
#define POWER_BUTTON GPIO_NUM_18

#define SAMPLE_RATE 16000

#define I2C_SDA_PIN GPIO_NUM_47
#define I2C_SCL_PIN GPIO_NUM_48
#define I2S_NUM 0
#define I2C_DEV_NUM I2C_NUM_0
#define I2S_MCLK_PIN GPIO_NUM_14
#define I2S_BCLK_PIN GPIO_NUM_15
#define I2S_WS_PIN GPIO_NUM_38
#define I2S_DOUT_PIN GPIO_NUM_45
#define I2S_DIN_PIN GPIO_NUM_16
#define MCLK_MULTIPLE 384
#define PA_CTRL_PIN GPIO_NUM_46

#endif
